### ISSUE TITLE
Excessive loading time

### ISSUE THREAD

**Issue by randomphrase** [ffevotte/clang-tags#8]
I just built and ran clang-tags on its own source code - and it took almost 3 hours at 100% CPU to complete the 'load' command. Is this to be expected?

This is running on a Mac OS X 10.9 system, built with clang 3.3 and boost 1.54 (both installed from MacPorts), as follows:

$ CC=clang-mp-3.3 CXX=clang++-mp-3.3 cmake -DCMAKE_BUILD_TYPE=Release -DLIBCLANG_ROOT=/opt/local/libexec/llvm-3.3/ -DCMAKE_EXPORT_COMPILE_COMMANDS=1 ..
$ make

Note that there is no support for strace on this system, so I had to comment out the relevant line in CMakeLists.txt. This seemed OK - at least it correctly picked up the compile_commands.json file.

I have the output of the load command but it's a bit too long to attach to this issue. I can email it if needed. However from observation of the progress, it seemed that the bulk of the time was spent in header files such as boost.

**Comment by ffevotte** [comment]
No, this certainly is not to be expected... There used to be a performance problem in the `load` command, but it should be fixed since e3e881f3733292412b0fd392dae939acc90ebca7, and it did not incur as much as 3h penalty (especially for such a small project as `clang-tags`).

Could you please show the commands you used after `make`? I suspect that you are not timing the `load` command, but rather `index`.

**Comment by randomphrase** [comment]
Fortunately I still have the terminal window open... Here is the relevant history extract, please excuse the embarrassing mistakes!

 1375  rm -r *
 1376  CC=clang-mp-3.3 CXX=clang++-mp-3.3 cmake -DCMAKE_BUILD_TYPE=Release -DLIBCLANG_ROOT=/opt/local/libexec/llvm-3.3/ -DCMAKE_EXPORT_COMPILE_COMMANDS=1 ..
 1377  less compile_commands.json
 1378  make
 1379  less env.
 1380  less env.sh
 1381  . env.sh
 1382  . ./env.sh
 1383  echo $SHELL
 1384  ninja
 1385  make
 1386  less env.
 1387  less env.sh
 1388  . ./env.sh
 1389  clang-tags start
 1390  ls
 1391  clang-tags load
 1392  clang-tags index

Note that in this case the env.sh file refused to load cleanly. This is because I am using zsh, which couldn't load the bash_completions extract.

Item 1384 is me running ninja through force of habit - obviously it didn't work.

**Comment by ffevotte** [comment]
OK, now I understand better. In my understanding, `load` (1391) should take almost no time. Then `index` (1392) is what takes you 3 hours.

Let me try to explain what happens. When running `clang-tags index`, you can provide exclusion paths in the following way:

```
clang-tags index --exclude "/opt"
```

When `clang-tags` traverses the AST to index things, it skips included files located under one of these excluded paths. This is because inserting tags in the database is not (yet?) very efficient, and we don't necessarily want to index system header files. The default exclusion path is `/usr` (which works well for my Linux box).

Judging from what you said in your initial message, you are using header files from libraries which are installed outside of `/usr`: at least `libclang` in `/opt` (which shouldn't make much of a difference since the API is very small) but probably also `Boost` (boost headers should not appear in the output if they were under `/usr`).

Could you please try to replace (1392) with:

```
clang-tags index --exclude "/opt" --exclude "/path/to/boost"
```

and see if indexing times become more acceptable? If so, I might add other default exclusion paths, maybe more appropriate to Mac OS X.

---

Also I'll try and fix the issues you mention regarding `strace` and `zsh` (see #9)

**Comment by randomphrase** [comment]
Thanks, can confirm that excluding `/opt` did the trick nicely, indexed in 35s on my machine. I'm not sure how this will scale to the monster codebase at $WORK but I'll give it a go and report back.

Just out of interest, what is the bottleneck with inserting tags into the database?

By the way, [MacPorts](http://www.macports.org) installs everything by default under `/opt/local`, including boost. I'm happy to create a 'port' of clang-tags, for other mac users to use.

**Comment by ffevotte** [comment]
I'm glad you could make it work. I'll add `/opt/local` to the list of default exclusion paths, which should not affect Linux users and will probably be a better default for Mac OS X.

For the biggest project I'm working on at $WORK (a few 100 kSLOC of C++), `clang-tags` takes around 10 minutes to index the sources.

I fear the performance problems when inserting tags in the database mostly come from my poor knowledge of SQL. Mostly I'm having problems with avoiding duplicate tags when reindexing a file which has changed. I currently avoid these by deleting all tags from a file before reindexing it. Also, I never know when/where to put SQL transactions and which SQL indices to create (if at all).

By the way, if you have some time, could you please test the `inotify` branch? It was primarily intended to add support for automatic detection of filesystem changes to reindex the code base. It uses Linux' `inotify` system, so you'll not benefit from it, but it should not break anything and be a bit more efficient. If you can confirm that it works on Mac OS X, I'll merge it to the master banch.

Here is how you should use it:

``` sh
    # Start the server
    clang-tags start

    # Add exclusion paths
    clang-tags config index.exclude -a /opt/local

    # Load the compilation database:
    # the server starts indexing the code base in the background
    clang-tags load

    # Wait for the indexing process to terminate
    clang-tags index

    # Hack
    touch ../src/main.cxx 

    # Ask for a reindexing of the source codebase
    # - only "main.cxx" should be reindexed so this should be quick
    # - on Linux systems, this step is automatically performed using inotify
    clang-tags index

    # Stop the server
    clang-tags stop
```

**Comment by randomphrase** [comment]
Confirm that the inotify branch works as expected on MacOS X.

By the way I think there is a typo in one the commands above. I think you meant to write `config -a index.exclude /opt/local` instead of `config index.exclude -a /opt/local`. The latter will cause the default exclude path of `/usr` to be replaced with `.../-a` and `/opt/local`. This means everything in `/usr` is indexed.

**Comment by ffevotte** [comment]
Thanks for doing the test! As soon as I get some time, I'll update the documentation and merge `inotify` into master (see issue #11)

I created issue #10 to deal with the problem you report regarding the position of the `-a` command-line switch.

**Comment by randomphrase** [comment]
Great work, thanks.
